name: Deploy Laravel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Prepare Laravel Directories
        run: |
          mkdir -p bootstrap/cache
          mkdir -p storage/framework/cache
          mkdir -p storage/framework/sessions
          mkdir -p storage/framework/views
          mkdir -p storage/logs
          chmod -R 775 bootstrap/cache storage

      - name: Install Composer Dependencies
        run: composer install --no-dev --prefer-dist --no-interaction

      - name: Laravel Optimize
        run: |
          php artisan config:cache
          php artisan route:cache
